"""add creator studio collaboration

Revision ID: 01f77611bde3
Revises: c8f3d2b05a21
Create Date: 2026-07-27 20:09:27.487994

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01f77611bde3'
down_revision: Union[str, Sequence[str], None] = 'c8f3d2b05a21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_projects',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'creator_id', 'name', name='uq_creator_projects_name')
    )
    with op.batch_alter_table('creator_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_projects_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index('ix_creator_projects_scope_updated', ['tenant_id', 'creator_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_projects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_projects_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_materials',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('project_id', sa.String(length=64), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('content_text', sa.Text(), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('tags_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['creator_projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_materials_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_materials_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_materials_project_id'), ['project_id'], unique=False)
        batch_op.create_index('ix_creator_materials_scope_updated', ['tenant_id', 'creator_id', 'updated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_materials_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_materials_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_project_tasks',
    sa.Column('project_id', sa.String(length=64), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['creator_projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['creator_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'task_id')
    )
    with op.batch_alter_table('creator_project_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_project_tasks_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_project_tasks_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_channel_variants',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('draft_version', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=False),
    sa.Column('adaptation_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['creator_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['creator_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'creator_id', 'idempotency_key_hash', name='uq_creator_channel_variants_idempotency')
    )
    with op.batch_alter_table('creator_channel_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_channel_variants_channel'), ['channel'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_channel_variants_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index('ix_creator_channel_variants_draft_created', ['draft_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_channel_variants_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_channel_variants_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_channel_variants_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_channel_variants_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_draft_branches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('source_draft_id', sa.String(length=64), nullable=False),
    sa.Column('source_version', sa.Integer(), nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['creator_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_draft_id'], ['creator_drafts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'creator_id', 'draft_id', name='uq_creator_draft_branch_target')
    )
    with op.batch_alter_table('creator_draft_branches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_draft_branches_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_draft_branches_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_draft_branches_source_draft_id'), ['source_draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_draft_branches_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_suggestions',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('draft_id', sa.String(length=64), nullable=False),
    sa.Column('base_version', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('replacement_text', sa.Text(), nullable=False),
    sa.Column('prefix_context', sa.Text(), nullable=False),
    sa.Column('suffix_context', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('evidence_ids_json', sa.JSON(), nullable=False),
    sa.Column('risk_note', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('model_provider', sa.String(length=64), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key_hash', sa.String(length=64), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('applied_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['draft_id'], ['creator_drafts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['creator_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'creator_id', 'idempotency_key_hash', name='uq_creator_suggestions_idempotency')
    )
    with op.batch_alter_table('creator_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_suggestions_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index('ix_creator_suggestions_draft_created', ['draft_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_suggestions_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_suggestions_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_suggestions_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_suggestions_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_task_materials',
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('material_id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['creator_materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['task_id'], ['creator_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id', 'material_id')
    )
    with op.batch_alter_table('creator_task_materials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_task_materials_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_task_materials_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('creator_feedback_events',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', sa.String(length=128), nullable=False),
    sa.Column('creator_id', sa.String(length=128), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=True),
    sa.Column('draft_id', sa.String(length=64), nullable=True),
    sa.Column('suggestion_id', sa.String(length=64), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['draft_id'], ['creator_drafts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['suggestion_id'], ['creator_suggestions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['creator_tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('creator_feedback_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_creator_feedback_events_creator_id'), ['creator_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_feedback_events_draft_id'), ['draft_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_feedback_events_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_feedback_events_suggestion_id'), ['suggestion_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_feedback_events_task_id'), ['task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_creator_feedback_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index('ix_creator_feedback_scope_created', ['tenant_id', 'creator_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creator_feedback_events', schema=None) as batch_op:
        batch_op.drop_index('ix_creator_feedback_scope_created')
        batch_op.drop_index(batch_op.f('ix_creator_feedback_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_feedback_events_task_id'))
        batch_op.drop_index(batch_op.f('ix_creator_feedback_events_suggestion_id'))
        batch_op.drop_index(batch_op.f('ix_creator_feedback_events_kind'))
        batch_op.drop_index(batch_op.f('ix_creator_feedback_events_draft_id'))
        batch_op.drop_index(batch_op.f('ix_creator_feedback_events_creator_id'))

    op.drop_table('creator_feedback_events')
    with op.batch_alter_table('creator_task_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_task_materials_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_task_materials_creator_id'))

    op.drop_table('creator_task_materials')
    with op.batch_alter_table('creator_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_suggestions_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_suggestions_task_id'))
        batch_op.drop_index(batch_op.f('ix_creator_suggestions_status'))
        batch_op.drop_index(batch_op.f('ix_creator_suggestions_kind'))
        batch_op.drop_index(batch_op.f('ix_creator_suggestions_draft_id'))
        batch_op.drop_index('ix_creator_suggestions_draft_created')
        batch_op.drop_index(batch_op.f('ix_creator_suggestions_creator_id'))

    op.drop_table('creator_suggestions')
    with op.batch_alter_table('creator_draft_branches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_draft_branches_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_draft_branches_source_draft_id'))
        batch_op.drop_index(batch_op.f('ix_creator_draft_branches_draft_id'))
        batch_op.drop_index(batch_op.f('ix_creator_draft_branches_creator_id'))

    op.drop_table('creator_draft_branches')
    with op.batch_alter_table('creator_channel_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_channel_variants_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_channel_variants_task_id'))
        batch_op.drop_index(batch_op.f('ix_creator_channel_variants_status'))
        batch_op.drop_index(batch_op.f('ix_creator_channel_variants_draft_id'))
        batch_op.drop_index('ix_creator_channel_variants_draft_created')
        batch_op.drop_index(batch_op.f('ix_creator_channel_variants_creator_id'))
        batch_op.drop_index(batch_op.f('ix_creator_channel_variants_channel'))

    op.drop_table('creator_channel_variants')
    with op.batch_alter_table('creator_project_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_project_tasks_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_project_tasks_creator_id'))

    op.drop_table('creator_project_tasks')
    with op.batch_alter_table('creator_materials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_materials_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_materials_status'))
        batch_op.drop_index('ix_creator_materials_scope_updated')
        batch_op.drop_index(batch_op.f('ix_creator_materials_project_id'))
        batch_op.drop_index(batch_op.f('ix_creator_materials_kind'))
        batch_op.drop_index(batch_op.f('ix_creator_materials_creator_id'))

    op.drop_table('creator_materials')
    with op.batch_alter_table('creator_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_creator_projects_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_creator_projects_status'))
        batch_op.drop_index('ix_creator_projects_scope_updated')
        batch_op.drop_index(batch_op.f('ix_creator_projects_creator_id'))

    op.drop_table('creator_projects')
    # ### end Alembic commands ###
