"""creator baseline

Revision ID: 44c80083ed3e
Revises: 
Create Date: 2026-07-24 22:53:11.958417

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "44c80083ed3e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creator_evaluation_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("dataset_id", sa.String(length=128), nullable=False),
        sa.Column("dataset_version", sa.String(length=128), nullable=False),
        sa.Column("dataset_sha256", sa.String(length=64), nullable=False),
        sa.Column("request_sha256", sa.String(length=64), nullable=False),
        sa.Column("candidate_name", sa.String(length=128), nullable=False),
        sa.Column("candidate_version", sa.String(length=128), nullable=False),
        sa.Column("evaluator_version", sa.String(length=512), nullable=False),
        sa.Column("baseline_evaluation_run_id", sa.String(length=64), nullable=True),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("report_sha256", sa.String(length=64), nullable=False),
        sa.Column("report_json", sa.JSON(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creator_evaluation_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_evaluation_runs_completed",
            ["tenant_id", "completed_at"],
            unique=False,
        )
        batch_op.create_index(
            "ix_creator_evaluation_runs_dataset",
            ["tenant_id", "dataset_id", "dataset_version"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_evaluation_runs_mode"), ["mode"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_evaluation_runs_outcome"), ["outcome"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_evaluation_runs_tenant_id"),
            ["tenant_id"],
            unique=False,
        )

    op.create_table(
        "creator_memory_profiles",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("bio", sa.Text(), nullable=False),
        sa.Column("expertise_tags_json", sa.JSON(), nullable=False),
        sa.Column("audience_segments_json", sa.JSON(), nullable=False),
        sa.Column("style_traits_json", sa.JSON(), nullable=False),
        sa.Column("preferred_formats_json", sa.JSON(), nullable=False),
        sa.Column("language", sa.String(length=32), nullable=False),
        sa.Column("explicit_preferences_json", sa.JSON(), nullable=False),
        sa.Column("inferred_preferences_json", sa.JSON(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "creator_id"),
    )
    op.create_table(
        "creator_outbox_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("aggregate_type", sa.String(length=64), nullable=False),
        sa.Column("aggregate_id", sa.String(length=64), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creator_outbox_events", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_outbox_aggregate",
            ["aggregate_type", "aggregate_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_creator_outbox_delivery", ["status", "available_at"], unique=False
        )
        batch_op.create_index(
            "ix_creator_outbox_lease",
            ["status", "lease_expires_at"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_outbox_events_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_outbox_events_topic"), ["topic"], unique=False
        )

    op.create_table(
        "creator_retrieval_documents",
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("document_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("tags_json", sa.JSON(), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=False),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("heat_score", sa.Float(), nullable=False),
        sa.Column("authority_score", sa.Float(), nullable=False),
        sa.Column("source_system", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.String(length=128), nullable=True),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("projection_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("tenant_id", "document_id"),
    )
    with op.batch_alter_table("creator_retrieval_documents", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_retrieval_scope_creator",
            ["tenant_id", "creator_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_creator_retrieval_scope_visibility",
            ["tenant_id", "status", "visibility", "published_at"],
            unique=False,
        )

    op.create_table(
        "creator_tasks",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("session_id", sa.String(length=128), nullable=True),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("goal_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("active_run_id", sa.String(length=64), nullable=False),
        sa.Column("final_artifact_id", sa.String(length=128), nullable=True),
        sa.Column("pending_decision_id", sa.String(length=128), nullable=True),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("cancel_requested", sa.Boolean(), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("creator_tasks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_active_run_id"),
            ["active_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_creator_id"), ["creator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_pending_decision_id"),
            ["pending_decision_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_creator_tasks_scope_status",
            ["tenant_id", "creator_id", "status"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tasks_trace_id"), ["trace_id"], unique=False
        )

    op.create_table(
        "creator_drafts",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("current_version", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("external_draft_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "tenant_id", "creator_id", "id", name="uq_creator_draft_scope"
        ),
    )
    with op.batch_alter_table("creator_drafts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_drafts_creator_id"), ["creator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_drafts_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_drafts_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_drafts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "creator_evaluation_case_results",
        sa.Column("id", sa.String(length=256), nullable=False),
        sa.Column("evaluation_run_id", sa.String(length=64), nullable=False),
        sa.Column("case_id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("runtime_run_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("outcome", sa.String(length=32), nullable=False),
        sa.Column("passed", sa.Boolean(), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=True),
        sa.Column("observation_sha256", sa.String(length=64), nullable=False),
        sa.Column("metrics_json", sa.JSON(), nullable=False),
        sa.Column("limitations_json", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_run_id"], ["creator_evaluation_runs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "evaluation_run_id",
            "case_id",
            name="uq_creator_evaluation_case_results_case",
        ),
    )
    with op.batch_alter_table(
        "creator_evaluation_case_results", schema=None
    ) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_evaluation_case_results_evaluation_run_id"),
            ["evaluation_run_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_evaluation_case_results_outcome"),
            ["outcome"],
            unique=False,
        )
        batch_op.create_index(
            "ix_creator_evaluation_case_results_task",
            ["tenant_id", "creator_id", "task_id"],
            unique=False,
        )

    op.create_table(
        "creator_idempotency_records",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("scope", sa.String(length=512), nullable=False),
        sa.Column("key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("response_json", sa.JSON(), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "scope", "key_hash", name="uq_creator_idempotency_scope_key"
        ),
    )
    with op.batch_alter_table("creator_idempotency_records", schema=None) as batch_op:
        batch_op.create_index(
            "ix_creator_idempotency_expires_at", ["expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_idempotency_records_task_id"),
            ["task_id"],
            unique=False,
        )

    op.create_table(
        "creator_runs",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("thread_id", sa.String(length=64), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("execution_attempts", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("lease_owner", sa.String(length=128), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("checkpoint_id", sa.String(length=128), nullable=True),
        sa.Column("pending_decision_id", sa.String(length=128), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("retryable", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id", "attempt", name="uq_creator_runs_task_attempt"),
        sa.UniqueConstraint("thread_id", name="uq_creator_runs_thread_id"),
    )
    with op.batch_alter_table("creator_runs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_runs_pending_decision_id"),
            ["pending_decision_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_runs_status"), ["status"], unique=False
        )
        batch_op.create_index(
            "ix_creator_runs_status_lease", ["status", "lease_expires_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_runs_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "creator_artifacts",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("step_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("producer", sa.String(length=128), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("content_json", sa.JSON(), nullable=False),
        sa.Column("parent_ids_json", sa.JSON(), nullable=False),
        sa.Column("metadata_json", sa.JSON(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["creator_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id",
            "step_id",
            "kind",
            "revision",
            name="uq_creator_artifacts_step_revision",
        ),
    )
    with op.batch_alter_table("creator_artifacts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_artifacts_creator_id"), ["creator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_artifacts_kind"), ["kind"], unique=False
        )
        batch_op.create_index(
            "ix_creator_artifacts_run_created", ["run_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_artifacts_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_artifacts_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            "ix_creator_artifacts_task_kind", ["task_id", "kind"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_artifacts_tenant_id"), ["tenant_id"], unique=False
        )

    op.create_table(
        "creator_human_decisions",
        sa.Column("id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=128), nullable=False),
        sa.Column("interrupt_id", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=128), nullable=False),
        sa.Column("allowed_actions_json", sa.JSON(), nullable=False),
        sa.Column("allowed_option_ids_json", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("submission_hash", sa.String(length=64), nullable=True),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=32), nullable=True),
        sa.Column("actor_id", sa.String(length=128), nullable=True),
        sa.Column("selected_option_id", sa.String(length=128), nullable=True),
        sa.Column("feedback", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["creator_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "interrupt_id", name="uq_creator_human_decisions_interrupt"
        ),
    )
    with op.batch_alter_table("creator_human_decisions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_human_decisions_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            "ix_creator_human_decisions_run_status", ["run_id", "status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_human_decisions_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_human_decisions_task_id"), ["task_id"], unique=False
        )

    op.create_table(
        "creator_run_events",
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("type", sa.String(length=128), nullable=False),
        sa.Column("payload_json", sa.JSON(), nullable=False),
        sa.Column("trace_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["run_id"], ["creator_runs.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "run_id", "sequence", name="uq_creator_run_events_sequence"
        ),
    )
    with op.batch_alter_table("creator_run_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_run_events_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_run_events_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            "ix_creator_run_events_task_sequence", ["task_id", "sequence"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_run_events_trace_id"), ["trace_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_run_events_type"), ["type"], unique=False
        )

    op.create_table(
        "creator_tool_calls",
        sa.Column("call_id", sa.String(length=64), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("task_id", sa.String(length=64), nullable=True),
        sa.Column("run_id", sa.String(length=64), nullable=True),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("caller", sa.String(length=128), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("risk", sa.String(length=32), nullable=False),
        sa.Column("arguments_sha256", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("result_sha256", sa.String(length=64), nullable=True),
        sa.Column("result_size_bytes", sa.Integer(), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("reserved_json", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["run_id"], ["creator_runs.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["task_id"], ["creator_tasks.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("call_id"),
    )
    with op.batch_alter_table("creator_tool_calls", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_creator_id"), ["creator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_run_id"), ["run_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_status"), ["status"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_task_id"), ["task_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_tenant_id"), ["tenant_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_tool_name"), ["tool_name"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_creator_tool_calls_trace_id"), ["trace_id"], unique=False
        )

    op.create_table(
        "creator_draft_versions",
        sa.Column("draft_id", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("tenant_id", sa.String(length=128), nullable=False),
        sa.Column("creator_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("content_markdown", sa.Text(), nullable=False),
        sa.Column("content_sha256", sa.String(length=64), nullable=False),
        sa.Column("source_artifact_id", sa.String(length=128), nullable=True),
        sa.Column("editor_type", sa.String(length=32), nullable=False),
        sa.Column("actor_id", sa.String(length=128), nullable=False),
        sa.Column("idempotency_scope", sa.String(length=256), nullable=False),
        sa.Column("idempotency_key_hash", sa.String(length=64), nullable=False),
        sa.Column("request_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["draft_id"], ["creator_drafts.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"], ["creator_artifacts.id"], ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("draft_id", "version"),
        sa.UniqueConstraint(
            "tenant_id",
            "creator_id",
            "idempotency_scope",
            "idempotency_key_hash",
            name="uq_creator_draft_version_idempotency",
        ),
    )
    with op.batch_alter_table("creator_draft_versions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_creator_draft_versions_creator_id"),
            ["creator_id"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_creator_draft_versions_tenant_id"),
            ["tenant_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("creator_draft_versions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_draft_versions_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_creator_draft_versions_creator_id"))

    op.drop_table("creator_draft_versions")
    with op.batch_alter_table("creator_tool_calls", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_trace_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_tool_name"))
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_task_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_status"))
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_run_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tool_calls_creator_id"))

    op.drop_table("creator_tool_calls")
    with op.batch_alter_table("creator_run_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_run_events_type"))
        batch_op.drop_index(batch_op.f("ix_creator_run_events_trace_id"))
        batch_op.drop_index("ix_creator_run_events_task_sequence")
        batch_op.drop_index(batch_op.f("ix_creator_run_events_task_id"))
        batch_op.drop_index(batch_op.f("ix_creator_run_events_run_id"))

    op.drop_table("creator_run_events")
    with op.batch_alter_table("creator_human_decisions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_human_decisions_task_id"))
        batch_op.drop_index(batch_op.f("ix_creator_human_decisions_status"))
        batch_op.drop_index("ix_creator_human_decisions_run_status")
        batch_op.drop_index(batch_op.f("ix_creator_human_decisions_run_id"))

    op.drop_table("creator_human_decisions")
    with op.batch_alter_table("creator_artifacts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_artifacts_tenant_id"))
        batch_op.drop_index("ix_creator_artifacts_task_kind")
        batch_op.drop_index(batch_op.f("ix_creator_artifacts_task_id"))
        batch_op.drop_index(batch_op.f("ix_creator_artifacts_run_id"))
        batch_op.drop_index("ix_creator_artifacts_run_created")
        batch_op.drop_index(batch_op.f("ix_creator_artifacts_kind"))
        batch_op.drop_index(batch_op.f("ix_creator_artifacts_creator_id"))

    op.drop_table("creator_artifacts")
    with op.batch_alter_table("creator_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_runs_task_id"))
        batch_op.drop_index("ix_creator_runs_status_lease")
        batch_op.drop_index(batch_op.f("ix_creator_runs_status"))
        batch_op.drop_index(batch_op.f("ix_creator_runs_pending_decision_id"))

    op.drop_table("creator_runs")
    with op.batch_alter_table("creator_idempotency_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_idempotency_records_task_id"))
        batch_op.drop_index("ix_creator_idempotency_expires_at")

    op.drop_table("creator_idempotency_records")
    with op.batch_alter_table(
        "creator_evaluation_case_results", schema=None
    ) as batch_op:
        batch_op.drop_index("ix_creator_evaluation_case_results_task")
        batch_op.drop_index(batch_op.f("ix_creator_evaluation_case_results_outcome"))
        batch_op.drop_index(
            batch_op.f("ix_creator_evaluation_case_results_evaluation_run_id")
        )

    op.drop_table("creator_evaluation_case_results")
    with op.batch_alter_table("creator_drafts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_drafts_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_creator_drafts_task_id"))
        batch_op.drop_index(batch_op.f("ix_creator_drafts_status"))
        batch_op.drop_index(batch_op.f("ix_creator_drafts_creator_id"))

    op.drop_table("creator_drafts")
    with op.batch_alter_table("creator_tasks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_tasks_trace_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tasks_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tasks_status"))
        batch_op.drop_index("ix_creator_tasks_scope_status")
        batch_op.drop_index(batch_op.f("ix_creator_tasks_pending_decision_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tasks_kind"))
        batch_op.drop_index(batch_op.f("ix_creator_tasks_creator_id"))
        batch_op.drop_index(batch_op.f("ix_creator_tasks_active_run_id"))

    op.drop_table("creator_tasks")
    with op.batch_alter_table("creator_retrieval_documents", schema=None) as batch_op:
        batch_op.drop_index("ix_creator_retrieval_scope_visibility")
        batch_op.drop_index("ix_creator_retrieval_scope_creator")

    op.drop_table("creator_retrieval_documents")
    with op.batch_alter_table("creator_outbox_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_outbox_events_topic"))
        batch_op.drop_index(batch_op.f("ix_creator_outbox_events_status"))
        batch_op.drop_index("ix_creator_outbox_lease")
        batch_op.drop_index("ix_creator_outbox_delivery")
        batch_op.drop_index("ix_creator_outbox_aggregate")

    op.drop_table("creator_outbox_events")
    op.drop_table("creator_memory_profiles")
    with op.batch_alter_table("creator_evaluation_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_creator_evaluation_runs_tenant_id"))
        batch_op.drop_index(batch_op.f("ix_creator_evaluation_runs_outcome"))
        batch_op.drop_index(batch_op.f("ix_creator_evaluation_runs_mode"))
        batch_op.drop_index("ix_creator_evaluation_runs_dataset")
        batch_op.drop_index("ix_creator_evaluation_runs_completed")

    op.drop_table("creator_evaluation_runs")
    # ### end Alembic commands ###
