from enum import StrEnum


class RiskType(StrEnum):
    NORMAL = "NORMAL"
    ADVERTISING = "ADVERTISING"
    ABUSE = "ABUSE"
    PRIVACY = "PRIVACY"


class PolicySeverity(StrEnum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ModerationContentType(StrEnum):
    TEXT = "TEXT"
    POST = "POST"
    COMMENT = "COMMENT"


class ModerationAction(StrEnum):
    PASS = "PASS"
    REJECT = "REJECT"
    LIMIT = "LIMIT"
    HUMAN_REVIEW = "HUMAN_REVIEW"


class ModerationTaskStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    WAITING_REVIEW = "WAITING_REVIEW"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class DecisionSource(StrEnum):
    AGENT = "AGENT"
    HUMAN = "HUMAN"
    SYSTEM = "SYSTEM"


class SignalSource(StrEnum):
    CONTENT = "CONTENT"
    COMMUNITY = "COMMUNITY"
    REPORT = "REPORT"


class ModerationSignalType(StrEnum):
    TEXT_PATTERN = "TEXT_PATTERN"
    REPORT_COUNT = "REPORT_COUNT"
    AUTHOR_VIOLATION_HISTORY = "AUTHOR_VIOLATION_HISTORY"
    CONTEXT_INCOMPLETE = "CONTEXT_INCOMPLETE"


class ActionLogEvent(StrEnum):
    TASK_CREATED = "TASK_CREATED"
    AGENT_DECIDED = "AGENT_DECIDED"
    REVIEW_REQUESTED = "REVIEW_REQUESTED"
    HUMAN_DECIDED = "HUMAN_DECIDED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    POLICY_CREATED = "POLICY_CREATED"
    CASE_CREATED = "CASE_CREATED"
    SIGNALS_CAPTURED = "SIGNALS_CAPTURED"
    REPORT_RECEIVED = "REPORT_RECEIVED"
    COMMUNITY_STATUS_UPDATED = "COMMUNITY_STATUS_UPDATED"
    CONTEXT_RETRIEVAL_FAILED = "CONTEXT_RETRIEVAL_FAILED"
    EVIDENCE_REVIEWED = "EVIDENCE_REVIEWED"
