CREATE TABLE IF NOT EXISTS scheduled_publications (
    id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    draft_id BIGINT UNSIGNED NOT NULL,
    run_at TIMESTAMP(3) NOT NULL,
    timezone VARCHAR(64) NOT NULL DEFAULT 'Asia/Shanghai',
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED' COMMENT 'SCHEDULED | PROCESSING | PUBLISHED | CANCELLED | FAILED',
    version INT NOT NULL DEFAULT 0,
    idempotency_key VARCHAR(128) NULL,
    published_post_id BIGINT UNSIGNED NULL,
    failure_code VARCHAR(64) NULL,
    failure_message VARCHAR(512) NULL,
    audit_actor VARCHAR(128) NULL,
    created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    cancelled_at TIMESTAMP(3) NULL,
    published_at TIMESTAMP(3) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_sp_user_idem (user_id, idempotency_key),
    KEY ix_sp_user_status (user_id, status),
    KEY ix_sp_run_at_status (run_at, status),
    KEY ix_sp_draft_id (draft_id),
    CONSTRAINT fk_sp_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_sp_draft FOREIGN KEY (draft_id) REFERENCES know_posts(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
