CREATE TABLE IF NOT EXISTS comments (
    id BIGINT UNSIGNED NOT NULL,
    post_id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    root_id BIGINT UNSIGNED NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    content VARCHAR(1000) NOT NULL,
    status VARCHAR(16) NOT NULL DEFAULT 'published',
    is_top TINYINT(1) NOT NULL DEFAULT 0,
    reply_count INT UNSIGNED NOT NULL DEFAULT 0,
    create_time DATETIME(3) NOT NULL,
    update_time DATETIME(3) NOT NULL,
    PRIMARY KEY (id),
    KEY ix_comments_post_top_ct (post_id, is_top, create_time, id),
    KEY ix_comments_parent_ct (parent_id, create_time, id),
    KEY ix_comments_root_ct (root_id, create_time, id),
    KEY ix_comments_user_ct (user_id, create_time),
    CONSTRAINT fk_comments_post FOREIGN KEY (post_id) REFERENCES know_posts(id),
    CONSTRAINT fk_comments_user FOREIGN KEY (user_id) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
